
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "analytics-backend/worker"


)

var tests = []testing.InternalTest{

	{"TestProcessAggregatedBatch_Success", _test.TestProcessAggregatedBatch_Success},

	{"TestProcessAggregatedBatch_Empty", _test.TestProcessAggregatedBatch_Empty},

	{"TestProcessAggregatedBatch_ReadError", _test.TestProcessAggregatedBatch_ReadError},

	{"TestProcessAggregatedBatch_DoesNotAckOnClickHouseFailure", _test.TestProcessAggregatedBatch_DoesNotAckOnClickHouseFailure},

	{"TestProcessAggregatedBatch_AcksEvenWhenIndexEnqueueFails", _test.TestProcessAggregatedBatch_AcksEvenWhenIndexEnqueueFails},

	{"TestProcessIndexBatch_AcksOnSuccess", _test.TestProcessIndexBatch_AcksOnSuccess},

	{"TestProcessIndexBatch_DoesNotAckOnIndexFailure", _test.TestProcessIndexBatch_DoesNotAckOnIndexFailure},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "analytics-backend/worker"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

